name = "Size Guide + Fit Finder"
client_id = "1f547dea664ef7e7ab09baad2ff831af"
application_url = "https://size-guide-app.jobspic.com"
embedded = true

[access]
scopes = "read_products"

[build]

[auth]
redirect_urls = [
  "https://size-guide-app.jobspic.com/api/auth/callback"
]

[webhooks]
api_version = "2026-07"

  [webhooks.privacy_compliance]
  customer_data_request_url = "https://size-guide-app.jobspic.com/api/webhooks/customer_data_request"
  customer_data_redaction_url = "https://size-guide-app.jobspic.com/api/webhooks/customer_data_redaction"
  shop_data_redaction_url = "https://size-guide-app.jobspic.com/api/webhooks/shop_data_redaction"

[app_proxy]
url = "https://size-guide-app.jobspic.com/apps/size-guide"
subpath = "size-guide"
prefix = "apps"

[pos]
embedded = false
